export const accessoryCharges = {
  "26' Straight Truck Show place Delivery": 400,
  "53' Semi Trailer Show Place Delivery": 600,
  "AM/PM Special": 50,
  "DG/Haz Mat | A, B Zone": 25,
  "DG/Haz Mat | C, D Zone": 50,
  "Downtown Area": 50,
  "Empty Pallet": 15,
  "Liftgate 1~4": 65,
  "Liftgate 5~8": 90,
  "Liftgate 9~12": 120,
  "Pallet Jack": 25,
  "Prepull": 50,
  "Residential Area": 50,
  "Same Day Delivery": 50,
  "Weekend Special": 150,
  "In/Out Charge": 10,
  "Inside Delivery | per 100Lbs": 0,
  "Volume Charge Per Pallet": 15,
  "Detention $60/Hour": 0,
  "COD | Collect On Delivery": 25,
  "Stop Over Charge": 50,
  "Storage Charge $10/Pallet/Per Day": 10,
  "THC + Processing Fee per $100 Covered": 0
}; 