// City -> delivery zone, from RateChart.xlsx (Zone Chart)
export const cityZones = [
  { city: "Addison", zone: "A" },
  { city: "Algonquin", zone: "A" },
  { city: "Alsip", zone: "C" },
  { city: "Antioch", zone: "E" },
  { city: "Arlington Heights", zone: "A" },
  { city: "Aurora", zone: "C" },
  { city: "Aux Sable", zone: "E" },
  { city: "Bannockburn", zone: "C" },
  { city: "Barrington", zone: "C" },
  { city: "Barrington Hills", zone: "C" },
  { city: "Bartlett", zone: "B" },
  { city: "Batavia", zone: "D" },
  { city: "Beach Park", zone: "E" },
  { city: "Bedford Park", zone: "C" },
  { city: "Bellwood", zone: "B" },
  { city: "Belvidere", zone: "E" },
  { city: "Bensenville", zone: "A" },
  { city: "Berkeley", zone: "A" },
  { city: "Berwyn", zone: "B" },
  { city: "Bloomingdale", zone: "B" },
  { city: "Blue Island", zone: "D" },
  { city: "Bolingbrook", zone: "C" },
  { city: "Braidwood", zone: "E" },
  { city: "Bridgeview", zone: "C" },
  { city: "Broadview", zone: "B" },
  { city: "Brookfield", zone: "B" },
  { city: "Buffalo Grove", zone: "B" },
  { city: "Burbank", zone: "C" },
  { city: "Burlington", zone: "E" },
  { city: "Burnham", zone: "E" },
  { city: "Burr Ridge", zone: "C" },
  { city: "Calumet City", zone: "E" },
  { city: "Calumet Park", zone: "E" },
  { city: "Carol Stream", zone: "B" },
  { city: "Carpentersville", zone: "C" },
  { city: "Cary", zone: "D" },
  { city: "Chicago A (up to 10mile)", zone: "A" },
  { city: "Chicago B (fr 10~15miles)", zone: "B" },
  { city: "Chicago C (fr 15~25miles)", zone: "C" },
  { city: "Chicago D (fr 25~40miles)", zone: "D" },
  { city: "Chicago Heights", zone: "E" },
  { city: "Chicago Ridge", zone: "D" },
  { city: "Cicero", zone: "C" },
  { city: "Clarendon Hills", zone: "B" },
  { city: "Country Club Hills", zone: "E" },
  { city: "Countryside", zone: "B" },
  { city: "Crest Hill", zone: "E" },
  { city: "Crestwood", zone: "C" },
  { city: "Crete", zone: "E" },
  { city: "Crystal Lake", zone: "D" },
  { city: "Darien", zone: "C" },
  { city: "De Kalb", zone: "E" },
  { city: "Deer Park", zone: "C" },
  { city: "Deerfield", zone: "C" },
  { city: "Des Plaines", zone: "A" },
  { city: "Dixmoor", zone: "E" },
  { city: "Dolton", zone: "D" },
  { city: "Downers Grove", zone: "B" },
  { city: "East Dundee", zone: "C" },
  { city: "East Hazel Crest", zone: "E" },
  { city: "Elgin", zone: "C" },
  { city: "Elk Grove Village", zone: "A" },
  { city: "Elmhurst", zone: "A" },
  { city: "Elmwood Park", zone: "A" },
  { city: "Elwood", zone: "E" },
  { city: "Evanston", zone: "C" },
  { city: "Evergreen Park", zone: "C" },
  { city: "Flossmoor", zone: "E" },
  { city: "Forest Park", zone: "B" },
  { city: "Forest View", zone: "C" },
  { city: "Fox River Grove", zone: "C" },
  { city: "Frankfort", zone: "E" },
  { city: "Franklin Park", zone: "A" },
  { city: "Geneva", zone: "C" },
  { city: "Genoa", zone: "E" },
  { city: "Gilbert", zone: "D" },
  { city: "Glen Ellyn", zone: "B" },
  { city: "Glencoe", zone: "B" },
  { city: "Glendale Heights", zone: "B" },
  { city: "Glenview", zone: "B" },
  { city: "Glenwood", zone: "C" },
  { city: "Golf", zone: "B" },
  { city: "Grayslake", zone: "D" },
  { city: "Great Lakes", zone: "E" },
  { city: "Gurnee", zone: "D" },
  { city: "Half Day", zone: "C" },
  { city: "Hampshire", zone: "E" },
  { city: "Harvard", zone: "E" },
  { city: "Harvey", zone: "D" },
  { city: "Harwood Heights", zone: "A" },
  { city: "Hazel Crest", zone: "E" },
  { city: "Hickory Hills", zone: "C" },
  { city: "Highland Park", zone: "B" },
  { city: "Highwood", zone: "C" },
  { city: "Hillside", zone: "B" },
  { city: "Hines", zone: "B" },
  { city: "Hinsdale", zone: "B" },
  { city: "Hodgkins", zone: "B" },
  { city: "Hoffman Estates", zone: "B" },
  { city: "Hometown", zone: "C" },
  { city: "Homewood", zone: "D" },
  { city: "Huntly", zone: "D" },
  { city: "Indian Head Park", zone: "C" },
  { city: "Inverness", zone: "B" },
  { city: "Itasca", zone: "A" },
  { city: "Joliet", zone: "D" },
  { city: "Justice", zone: "C" },
  { city: "Kaneville", zone: "E" },
  { city: "Kenilworth", zone: "C" },
  { city: "Kirkland", zone: "E" },
  { city: "La Fox", zone: "E" },
  { city: "La Grange", zone: "B" },
  { city: "Lake Barrington", zone: "B" },
  { city: "Lake Bluff", zone: "C" },
  { city: "Lake Forest", zone: "C" },
  { city: "Lake In the Hills", zone: "C" },
  { city: "Lake Villa", zone: "E" },
  { city: "Lake Zurich", zone: "C" },
  { city: "Lansing", zone: "E" },
  { city: "Lemont", zone: "C" },
  { city: "Libertyville", zone: "C" },
  { city: "Lily Lake", zone: "E" },
  { city: "Lincolnshire", zone: "C" },
  { city: "Lincolnwood", zone: "B" },
  { city: "Lindenwood", zone: "E" },
  { city: "Lisbon", zone: "E" },
  { city: "Lisle", zone: "B" },
  { city: "Lockport", zone: "D" },
  { city: "Lombard", zone: "B" },
  { city: "Long Grove", zone: "C" },
  { city: "Loves Park", zone: "E" },
  { city: "Lynwood", zone: "E" },
  { city: "Lyons", zone: "B" },
  { city: "Maple Park", zone: "E" },
  { city: "Marengo", zone: "E" },
  { city: "Markham", zone: "E" },
  { city: "Matteson", zone: "E" },
  { city: "Maywood", zone: "B" },
  { city: "McCook", zone: "B" },
  { city: "McHenry", zone: "D" },
  { city: "Melrose Park", zone: "B" },
  { city: "Midlothian", zone: "D" },
  { city: "Mokena", zone: "E" },
  { city: "Monee", zone: "E" },
  { city: "Montgomery", zone: "D" },
  { city: "Morris", zone: "E" },
  { city: "Morton Grove", zone: "B" },
  { city: "Mt. Prospect", zone: "A" },
  { city: "Mundelein", zone: "C" },
  { city: "Naperville", zone: "C" },
  { city: "New Lenox", zone: "D" },
  { city: "Niles", zone: "B" },
  { city: "Norridge", zone: "A" },
  { city: "North Aurora", zone: "D" },
  { city: "North Chicago", zone: "D" },
  { city: "North Riverside", zone: "B" },
  { city: "Northbrook", zone: "B" },
  { city: "Northfield", zone: "B" },
  { city: "Northlake", zone: "A" },
  { city: "Oak Brook", zone: "B" },
  { city: "Oak Brook Terrace", zone: "B" },
  { city: "Oak Forest", zone: "D" },
  { city: "Oak Lawn", zone: "C" },
  { city: "Oak Park", zone: "B" },
  { city: "Olympia Fields", zone: "E" },
  { city: "Orland Park", zone: "D" },
  { city: "Oswego", zone: "E" },
  { city: "Palatine", zone: "B" },
  { city: "Palos Heights", zone: "C" },
  { city: "Palos Park", zone: "C" },
  { city: "Park city", zone: "D" },
  { city: "Park Forest", zone: "E" },
  { city: "Park Ridge", zone: "A" },
  { city: "Peotone", zone: "E" },
  { city: "Pingree Grove", zone: "E" },
  { city: "Plainfield", zone: "D" },
  { city: "Plano", zone: "E" },
  { city: "Plato Center", zone: "E" },
  { city: "Posen", zone: "D" },
  { city: "Prospect Heights", zone: "B" },
  { city: "Richton Park", zone: "E" },
  { city: "Riley", zone: "E" },
  { city: "Ringwood", zone: "E" },
  { city: "River Forest", zone: "B" },
  { city: "River Grove", zone: "A" },
  { city: "Riverdale", zone: "E" },
  { city: "Riverwood", zone: "B" },
  { city: "Robbins", zone: "D" },
  { city: "Rockdale", zone: "E" },
  { city: "Rockford", zone: "E" },
  { city: "Rolling Meadows", zone: "A" },
  { city: "Romeoville", zone: "C" },
  { city: "Roscoe", zone: "E" },
  { city: "Roselle", zone: "A" },
  { city: "Rosemont", zone: "A" },
  { city: "Round Lake", zone: "E" },
  { city: "Schaumburg", zone: "A" },
  { city: "Schiller Park", zone: "A" },
  { city: "Shorewood", zone: "D" },
  { city: "Skokie", zone: "B" },
  { city: "Sleepy Hollow", zone: "E" },
  { city: "South Barrington", zone: "B" },
  { city: "South Chicago Heights", zone: "E" },
  { city: "South Elgin", zone: "C" },
  { city: "South Holland", zone: "D" },
  { city: "Spring Grove", zone: "E" },
  { city: "St. Charles", zone: "C" },
  { city: "Steger", zone: "E" },
  { city: "Stickney", zone: "C" },
  { city: "Stone Park", zone: "A" },
  { city: "Streamwood", zone: "B" },
  { city: "Sugar Grove", zone: "E" },
  { city: "Summit", zone: "C" },
  { city: "Sycamore", zone: "E" },
  { city: "Tinley Park", zone: "D" },
  { city: "Union", zone: "E" },
  { city: "University Park", zone: "E" },
  { city: "Vernon Hills", zone: "C" },
  { city: "Villa Park", zone: "A" },
  { city: "Volo", zone: "D" },
  { city: "Wadsworth", zone: "E" },
  { city: "Warrenville", zone: "C" },
  { city: "Wasco", zone: "D" },
  { city: "Wauconda", zone: "D" },
  { city: "Waukegan", zone: "D" },
  { city: "West Chester", zone: "B" },
  { city: "West Dundee", zone: "C" },
  { city: "Western Springs", zone: "B" },
  { city: "Westmont", zone: "B" },
  { city: "West\u00a0Chicago", zone: "C" },
  { city: "Wheaton", zone: "B" },
  { city: "Wheeling", zone: "B" },
  { city: "Willow Springs", zone: "C" },
  { city: "Willowbrook", zone: "C" },
  { city: "Wilmette", zone: "B" },
  { city: "Wilmington", zone: "E" },
  { city: "Winfield", zone: "B" },
  { city: "Winnetka", zone: "B" },
  { city: "Wood Dale", zone: "A" },
  { city: "Woodridge", zone: "C" },
  { city: "Woodstock", zone: "E" },
  { city: "Worth", zone: "C" },
  { city: "Yorkville", zone: "E" },
  { city: "Zion", zone: "E" },
];
